server:
  port: 8088
zuul:
  routes:
    myServer:
      path: /myServer/**
      serviceId: eruake-client
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      ignoredHeaders: Header2
    testForward:
      path: /fo/**
      url: forward:/receive
    v:
      path: /h/**
      url: http://localhost:8082/person/
    eruake-client:
      path: /server/**
ribbon:
  okhttp:
    enable: true
spring:
  application:
    name: config-zuul
  rabbitmq:
    host: 192.168.1.5
    port: 5672
    username: devin
    password: devinpwd163
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: dev
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/