server:
  port: 10000
spring:
  application:
    name: eureka-bus
  rabbitmq:
    host: 192.168.1.5
    port: 5672
    username: devin
    password: devinpwd163
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/