#server:
#  port: 8888
##  port: 8889
#spring:
#  application:
#  name: first-cloud-server
#
#eureka:
#  instance:
#    hostname: localhost
#  server:
#    enable-self-preservation: false # 关闭Eureka的自我保护模式
#    eviction-interval-timer-in-ms: 5000 # 将定时器开始时间定为每5秒（单位：毫秒）
#  client:
#    registerWithEureka: false
#    fetchRegistry:  false
#    serviceUrl:
#      defaultZone:  http://${eureka.instance.hostname}:8889/eureka/
#      defaultZone:  http://${eureka.instance.hostname}:8888/eureka/
server:
  port: 8761
spring:
  application:
    name: first-cloud-server
  profiles: slave1
eureka:
  instance:
    hostname: slave1
  server:
    enable-self-preservation: false # 关闭Eureka的自我保护模式
    eviction-interval-timer-in-ms: 5000 # 将定时器开始时间定为每5秒（单位：毫秒）
  client:
    registerWithEureka: false
    fetchRegistry:  false
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
---
server:
  port: 8762
spring:
  application:
    name: first-cloud-server
  profiles: slave2
eureka:
  instance:
    hostname: slave2
  server:
    enable-self-preservation: false # 关闭Eureka的自我保护模式
    eviction-interval-timer-in-ms: 5000 # 将定时器开始时间定为每5秒（单位：毫秒）
  client:
    registerWithEureka: false
    fetchRegistry:  false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/