eureka:
  instance:
    lease-renewal-interval-in-seconds: 10  # 心跳设置（单位：s）
    hostname: localhost
    metadata-map:
      company-name: aitemi  #公司名称
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/ # ,http://localhost:8762/eureka/  # 注册到两个服务端
#user-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.devin.eruakeclient.rule.MyRule # Ribbon，指定规则
# 可访问全部敏感端口
# /evn 服务的全部环境变量信息
# /health 当前服务状态
endpoints:
  sensitive: false
server:
  port: 9090
  application:
    name: eruake-client
##开启feign开关
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    ##全局方法使用default
    HelloClient#toHello():
      execution:
        isolation:
          thread:
          ##超时时间
            timeoutInMilliseconds: 500
      circuitBreaker:
      ##每秒3次请求
        requestVolumeThreshold: 3
spring:
  application:
    name: eruake-client
# 均使用默认的配置，所以可以无需配置，需要修改时，再配置
#rabbitmq:
#  host: localhost
#  port: 5762
#  username: guest
#  password: guest
# 日志配置
logging:
  level:
    com.netflix: INFO